[package]
name = "trajectory_optimizer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
array2d = "0.3.0"
rand = "0.8.4"
colors-transform = "0.2.11"
sdl2 = "0.32.1"